import { useState } from "react";
import { Copy, Plus, Trash2 } from "lucide-react";
import Field from "../../../components/ui/Field";
import Toggle from "../../../components/ui/Toggle";

function CommercialStep({ form, setForm }) {
  const [percent, setPercent] = useState(true);
  const [amc, setAmc] = useState(true);
  if (form.model === "SaaS") return <div className="grid gap-5 md:grid-cols-2"><Field label="Plan / tier"><select className="field"><option>Pro</option><option>Basic</option><option>Enterprise</option></select></Field><Field label="Subscription amount"><div className="flex gap-2"><select className="field !w-24"><option>INR</option><option>EUR</option></select><input className="field" defaultValue="150000" /></div></Field><Field label="Billing frequency"><select className="field"><option>Annual</option><option>Monthly</option><option>Quarterly</option></select></Field><Field label="Number of seats"><input className="field" type="number" defaultValue="60" /></Field><Field label="Start date"><input className="field" type="date" defaultValue="2026-10-01" /></Field><div className="rounded-xl border p-4"><span className="label">Auto-renewal</span><div className="mt-3 flex items-center gap-3"><Toggle on={amc} setOn={setAmc} /><span className="text-sm text-slate-500">{amc ? "Enabled" : "Disabled"}</span></div></div></div>;
  if (form.model === "License") return <div className="grid gap-5 md:grid-cols-2"><Field label="License type"><select className="field"><option>Perpetual</option><option>Term-based</option></select></Field><Field label="Number of licenses"><input className="field" type="number" defaultValue="100" /></Field><Field label="License fee"><div className="flex gap-2"><select className="field !w-24"><option>INR</option><option>EUR</option></select><input className="field" defaultValue="125000" /></div></Field><div className="rounded-xl border p-4"><span className="label">AMC / Maintenance</span><div className="mt-3 flex items-center gap-3"><Toggle on={amc} setOn={setAmc} /><span className="text-sm text-slate-500">{amc ? "18% annually" : "Not included"}</span></div>{amc && <input className="field !mt-3" defaultValue="18%" />}</div></div>;
  return <div><div className="grid gap-5 md:grid-cols-2"><Field label="Service line description"><input className="field" defaultValue="Digital transformation & implementation" /></Field><Field label="Total contract value"><div className="flex gap-2"><select className="field !w-24"><option>INR</option><option>EUR</option></select><input className="field" defaultValue="3250000" /></div></Field></div>
    <div className="mt-7 flex items-center justify-between"><div><h3 className="text-lg font-bold">Milestone rules</h3><p className="text-sm text-slate-400">Configure when and how each amount becomes billable.</p></div><button className="btn-secondary"><Plus size={16} />Add milestone</button></div>
    <div className="mt-4 overflow-hidden rounded-2xl border">
      <div className="flex items-center justify-between bg-slate-50 px-5 py-3"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-ink text-xs font-bold text-white">1</span><span className="text-sm font-bold">Discovery & solution blueprint</span></div><div className="flex gap-1"><button className="btn-ghost !p-2"><Copy size={15} /></button><button className="btn-ghost !p-2 text-rose-500"><Trash2 size={15} /></button></div></div>
      <div className="grid gap-4 p-5 lg:grid-cols-12"><div className="lg:col-span-3"><Field label="Due date"><input className="field" type="date" defaultValue="2026-11-15" /></Field></div><div className="lg:col-span-4"><span className="label">Billing basis</span><div className="mt-2 flex rounded-xl bg-slate-100 p-1"><button onClick={() => setPercent(false)} className={`flex-1 rounded-lg px-2 py-2 text-xs font-bold ${!percent ? "bg-white shadow" : "text-slate-400"}`}>Fixed amount</button><button onClick={() => setPercent(true)} className={`flex-1 rounded-lg px-2 py-2 text-xs font-bold ${percent ? "bg-white shadow" : "text-slate-400"}`}>% of value</button></div></div><div className="lg:col-span-2"><Field label={percent ? "Percentage" : "Amount"}><input className="field" defaultValue={percent ? "25%" : "812,500"} /></Field></div><div className="lg:col-span-3"><Field label="Computed amount"><div className="field bg-slate-50 font-bold text-slate-700">₹8,12,500</div></Field></div><div className="lg:col-span-7"><Field label="Completion criteria"><input className="field" defaultValue="Blueprint approved by client sponsor" /></Field></div><div className="lg:col-span-5"><Field label="Tax rule"><select className="field"><option>Use contract default · IGST 18%</option><option>No tax / Nil rated</option><option>Custom override</option></select></Field></div></div>
      <div className="border-t bg-moss-50/60 px-5 py-3 text-xs font-medium text-moss-700">This rule will create an invoice for ₹8,12,500 + ₹1,46,250 IGST when the milestone is ready.</div>
    </div>
  </div>;
}
export default CommercialStep;
