import { useState } from "react";
import { Plus, Sparkles } from "lucide-react";
import Field from "../../../components/ui/Field";
import Toggle from "../../../components/ui/Toggle";

function TaxStep({ form }) {
  const [override, setOverride] = useState(false);
  const [enabled, setEnabled] = useState([true, true, true]);
  const exportTax = form.country !== "India";
  const intra = form.country === "India" && form.state === "West Bengal" && form.entity.includes("West Bengal");
  const tax = exportTax ? { title: "Export of Service · 0% GST", body: `${form.country} customer → India billing entity`, detail: "Zero-rated supply · VAT self-assessed by customer under reverse charge" } : intra ? { title: "CGST 9% + SGST 9%", body: "West Bengal customer → West Bengal billing entity", detail: "Intra-state supply · 18% total GST" } : { title: "IGST 18%", body: `${form.state} customer → West Bengal billing entity`, detail: "Inter-state supply · 18% integrated GST" };
  const rules = [["Milestone due", "Project Manager, Finance", "Email", "7 days before"], ["Invoice generated", "Finance Approver", "Email + In-app", "Immediately"], ["Contract nearing expiry", "Account Manager", "Email", "30 days before"]];
  return <div className="space-y-7"><div><h3 className="mb-3 text-lg font-bold">Tax & jurisdiction</h3><div className="relative overflow-hidden rounded-2xl border border-moss-500/30 bg-moss-50 p-5"><div className="absolute right-0 top-0 h-28 w-28 rounded-full bg-moss-200/50 blur-2xl" /><div className="relative flex flex-col gap-4 sm:flex-row sm:items-start"><div className="grid h-11 w-11 place-items-center rounded-xl bg-moss-600 text-white"><Sparkles size={20} /></div><div className="flex-1"><div className="text-xs font-bold uppercase tracking-wider text-moss-600">Auto-detected tax treatment</div><h3 className="mt-1 text-xl font-bold text-moss-700">{tax.title}</h3><p className="mt-1 text-sm text-slate-600">{tax.body}</p><p className="mt-3 inline-flex rounded-lg bg-white/70 px-3 py-2 text-xs font-medium text-slate-500">{tax.detail}</p></div><button onClick={() => setOverride(!override)} className="btn-secondary !border-moss-200">{override ? "Use suggestion" : "Override"}</button></div></div>{override && <div className="mt-3 grid gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 md:grid-cols-2"><Field label="Tax type"><select className="field"><option>IGST</option><option>CGST + SGST</option><option>Export / Zero-rated</option></select></Field><Field label="Rate"><input className="field" defaultValue="18%" /></Field><p className="text-xs text-amber-700 md:col-span-2">Manual overrides are recorded in the audit trail and require finance approval.</p></div>}</div>
    <div><div className="mb-3 flex items-end justify-between"><div><h3 className="text-lg font-bold">Notification rules</h3><p className="text-sm text-slate-400">Pre-filled from workspace defaults. Adjust for this contract.</p></div><button className="btn-secondary"><Plus size={15} />Add rule</button></div><div className="overflow-x-auto rounded-2xl border"><table className="w-full min-w-[750px]"><thead className="bg-slate-50"><tr>{["On", "Event", "Notify", "Channel", "Timing"].map((x) => <th key={x} className="table-head">{x}</th>)}</tr></thead><tbody>{rules.map((r, i) => <tr key={r[0]}><td className="table-cell"><Toggle on={enabled[i]} setOn={(v) => setEnabled(enabled.map((x, j) => j === i ? v : x))} /></td>{r.map((x, j) => <td key={j} className={`table-cell ${j === 0 ? "font-semibold" : "text-slate-500"}`}>{x}</td>)}</tr>)}</tbody></table></div></div>
  </div>;
}
export default TaxStep;
