import { useState } from "react";
import { ArrowLeft, Sparkles } from "lucide-react";
import { contracts } from "../../data/mockData";
import Field from "../../components/ui/Field";
import PageHead from "../../components/ui/PageHead";
import InvoicePaper from "./InvoicePaper";

function GenerateInvoice({ setPage, notify }) {
  const [stage, setStage] = useState(0);
  const [contract, setContract] = useState("CTR-2026-041");
  const selected = contracts.find((c) => c.id === contract) || contracts[0];
  return <><button onClick={() => stage ? setStage(0) : setPage("invoices")} className="btn-ghost mb-4 !px-0"><ArrowLeft size={17} />{stage ? "Change trigger" : "Back to invoices"}</button><PageHead eyebrow={`Generate invoice · ${stage ? "Preview" : "Select trigger"}`} title={stage ? "Proforma invoice" : "What are you billing?"} desc={stage ? "Review the auto-generated invoice before sending it for approval." : "Choose an approved contract and LedgerFlow will apply its billing and tax rules."} />
    {stage === 0 ? <div className="mx-auto max-w-3xl panel p-6 sm:p-8"><div className="mb-6 rounded-2xl bg-moss-50 p-5"><div className="flex gap-3"><Sparkles className="text-moss-600" size={20}/><div><p className="font-bold text-moss-700">Contract-driven invoicing</p><p className="mt-1 text-sm text-moss-700/70">Line items, tax, entity and payment terms will be pulled from the selected contract.</p></div></div></div><div className="space-y-5"><Field label="Approved contract"><select value={contract} onChange={(e)=>setContract(e.target.value)} className="field">{contracts.filter((c)=>c.status==="Approved").map((c)=><option key={c.id} value={c.id}>{c.id} · {c.customer} · {c.model}</option>)}</select></Field><div className="grid gap-3 rounded-2xl border p-4 sm:grid-cols-3">{[["Customer",selected.customer],["Billing model",selected.model],["Tax treatment",selected.tax]].map(([a,b])=><div key={a}><p className="text-xs text-slate-400">{a}</p><p className="mt-1 text-sm font-bold">{b}</p></div>)}</div><Field label={selected.model === "Project" ? "Milestone to invoice" : selected.model === "SaaS" ? "Billing period" : "Billing event"}><select className="field"><option>{selected.model === "Project" ? "Milestone 1 · Discovery & blueprint" : selected.model === "SaaS" ? "September 2026" : "Initial license fee"}</option><option>{selected.model === "Project" ? "Milestone 2 · Implementation & UAT" : "Next billing event"}</option></select></Field><button onClick={()=>setStage(1)} className="btn-primary w-full !py-3.5"><Sparkles size={17}/>Generate proforma</button></div></div> :
      <div className="grid gap-5 xl:grid-cols-[1fr_290px]"><InvoicePaper/><div className="space-y-4"><div className="panel p-5"><h3 className="font-bold">Tax applied</h3><div className="mt-3 rounded-xl bg-moss-50 p-3"><p className="text-sm font-bold text-moss-700">IGST · 18%</p><p className="mt-1 text-xs text-moss-600">Delhi → West Bengal</p></div><button className="mt-3 text-xs font-bold text-amber-600">Override tax treatment</button></div><div className="panel p-5"><h3 className="font-bold">Next step</h3><p className="mt-2 text-sm leading-6 text-slate-500">Finance Approver will receive an in-app and email notification.</p><button onClick={()=>{notify("Invoice submitted for finance approval");setPage("invoices");}} className="btn-primary mt-4 w-full">Submit for approval</button><button onClick={()=>notify("Draft invoice saved")} className="btn-secondary mt-2 w-full">Save as draft</button></div></div></div>}</>;
}
export default GenerateInvoice;
