import { ReceiptText } from "lucide-react";

function InvoicePaper({ status = "Proforma" }) {
  return <div className="mx-auto max-w-4xl rounded-sm border bg-white p-6 shadow-xl shadow-slate-200/60 sm:p-10">
    <div className="flex items-start justify-between border-b pb-7"><div><div className="mb-4 flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white"><ReceiptText size={18}/></div><b>Matrix Media Solutions</b></div><p className="text-xs leading-5 text-slate-500">22 Park Street, Kolkata, West Bengal 700016<br/>GSTIN: 19AABCM1234F1Z5</p></div><div className="text-right"><h2 className="text-3xl font-bold uppercase text-slate-300">{status}</h2><p className="mt-2 text-sm font-bold">MM-IN-WB-0185</p><p className="mt-1 text-xs text-slate-400">21 September 2026</p></div></div>
    <div className="grid gap-6 border-b py-7 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Bill to</p><p className="mt-2 font-bold">Capital Retail Solutions</p><p className="mt-1 text-xs leading-5 text-slate-500">Connaught Place, New Delhi 110001<br/>GSTIN: 07AACCR8890H1Z4</p></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Payment details</p><p className="mt-2 text-sm"><b>Due:</b> 21 October 2026</p><p className="mt-1 text-sm"><b>Terms:</b> Net 30 days</p></div></div>
    <div className="py-7"><div className="grid grid-cols-[1fr_60px_110px_120px] bg-slate-50 px-4 py-3 text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>Description</span><span>Qty</span><span>Rate</span><span className="text-right">Amount</span></div><div className="grid grid-cols-[1fr_60px_110px_120px] px-4 py-5 text-sm"><div><b>Discovery & solution blueprint</b><p className="mt-1 text-xs text-slate-400">Milestone 1 · Retail commerce transformation</p></div><span>1</span><span>₹8,12,500</span><b className="text-right">₹8,12,500</b></div></div>
    <div className="ml-auto w-full max-w-sm space-y-3 border-t pt-5 text-sm"><div className="flex justify-between text-slate-500"><span>Subtotal</span><span>₹8,12,500</span></div><div className="flex justify-between text-slate-500"><span>IGST · 18%</span><span>₹1,46,250</span></div><div className="flex justify-between border-t pt-4 text-lg font-bold"><span>Total</span><span>₹9,58,750</span></div><p className="text-right text-[10px] text-slate-400">Nine lakh fifty-eight thousand seven hundred fifty rupees only</p></div>
    <div className="mt-10 rounded-xl bg-slate-50 p-4 text-xs text-slate-500"><b className="text-slate-700">Bank details</b><br/>HDFC Bank · A/C 50200001234567 · IFSC HDFC0001234</div>
  </div>;
}
export default InvoicePaper;
