import { useState } from "react";
import { Check } from "lucide-react";
import Badge from "../components/ui/Badge";
import Field from "../components/ui/Field";
import PageHead from "../components/ui/PageHead";

function ApprovalsPage({ notify }) {
  const [tab, setTab] = useState("Contracts");
  const [done, setDone] = useState(false);
  return <><PageHead eyebrow="Review queue" title="Approvals" desc="Review commercial terms and generated invoices before they become final." /><div className="mb-5 inline-flex rounded-xl bg-slate-200/60 p-1">{["Contracts","Invoices"].map((x)=><button onClick={()=>{setTab(x);setDone(false);}} key={x} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab===x?"bg-white shadow text-ink":"text-slate-500"}`}>{x} <span className="ml-1 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700">1</span></button>)}</div>
    {done ? <div className="panel grid min-h-80 place-items-center p-8 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-moss-50 text-moss-600"><Check size={25}/></div><h2 className="mt-4 text-xl font-bold">All done here</h2><p className="mt-2 text-sm text-slate-400">This item has been approved and the owner was notified.</p></div></div> :
    <div className="grid gap-5 lg:grid-cols-[330px_1fr]"><div className="panel h-fit p-3"><div className="rounded-xl border-2 border-moss-500 bg-moss-50/40 p-4"><div className="flex justify-between"><Badge>Pending Approval</Badge><span className="text-xs text-slate-400">5d</span></div><p className="mt-4 font-bold">{tab==="Contracts"?"Capital Retail Solutions":"Northline Software GmbH"}</p><p className="mt-1 text-xs text-slate-400">{tab==="Contracts"?"CTR-2026-040 · Project":"MM-IN-WB-0182 · License"}</p><p className="mt-4 text-lg font-bold">{tab==="Contracts"?"₹32,50,000":"€125,000"}</p></div></div><div className="panel p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-moss-600">{tab.slice(0,-1)} review</p><h2 className="mt-1 text-2xl font-bold">{tab==="Contracts"?"Retail commerce transformation":"Initial perpetual license fee"}</h2></div><Badge>Pending Approval</Badge></div><div className="my-6 border-t"/><div className="grid gap-5 sm:grid-cols-3">{[["Customer",tab==="Contracts"?"Capital Retail Solutions":"Northline Software GmbH"],["Billing model",tab==="Contracts"?"Project":"License"],["Tax",tab==="Contracts"?"IGST 18%":"Export · 0%"],["Value",tab==="Contracts"?"₹32,50,000":"€125,000"],["Billing entity","Matrix Media — India"],["Submitted by","Atanu Dey"]].map(([a,b])=><div key={a}><p className="text-xs text-slate-400">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div><Field label="Approval comment (optional)"><textarea className="field min-h-24" placeholder="Add context for the submitter..."/></Field><div className="mt-5 flex justify-end gap-3"><button onClick={()=>notify(`${tab.slice(0,-1)} sent back for changes`)} className="btn-secondary !text-rose-600">Reject</button><button onClick={()=>{setDone(true);notify(`${tab.slice(0,-1)} approved successfully`);}} className="btn-primary"><Check size={16}/>Approve</button></div></div></div>}</>;
}
export default ApprovalsPage;
