import { ArrowLeft, Check, CheckCircle2, ReceiptText } from "lucide-react";
import { contracts } from "../../data/mockData";
import ActionMenu from "../../components/ui/ActionMenu";
import Badge from "../../components/ui/Badge";
import PageHead from "../../components/ui/PageHead";

function ContractDetail({ contract, setPage, notify }) {
  const c = contract || contracts[0];
  return <><button onClick={() => setPage("contracts")} className="btn-ghost mb-4 !px-0"><ArrowLeft size={17} />All contracts</button>
    <PageHead eyebrow={c.id} title={c.customer} desc={`${c.location} · ${c.entity}`} action={<div className="flex gap-2"><ActionMenu buttonClassName="btn-secondary !px-3" onEdit={()=>{notify("Contract opened for editing");setPage("new-contract");}} onDelete={()=>{notify("Contract deleted");setPage("contracts");}}/>{c.status === "Approved" && <button onClick={() => setPage("generate-invoice")} className="btn-primary"><ReceiptText size={17} />Generate invoice</button>}</div>} />
    <div className="panel mb-5 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><Badge>{c.status}</Badge><p className="mt-2 text-xs text-slate-400">Last updated 18 Sep 2026, 4:32 PM</p></div><div className="flex min-w-[500px] max-w-2xl flex-1 items-center">{["Draft", "Submitted", "Approved"].map((x, i) => <div key={x} className="flex flex-1 items-center last:flex-none"><div className="text-center"><span className={`mx-auto grid h-8 w-8 place-items-center rounded-full ${i < (c.status === "Approved" ? 3 : 2) ? "bg-moss-600 text-white" : "bg-slate-100 text-slate-400"}`}><Check size={14} /></span><p className="mt-1 text-[10px] font-bold">{x}</p></div>{i < 2 && <div className={`mx-2 h-px flex-1 ${i < (c.status === "Approved" ? 2 : 1) ? "bg-moss-500" : "bg-slate-200"}`} />}</div>)}</div></div></div>
    <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="panel p-6"><h2 className="text-lg font-bold">Commercial summary</h2><div className="mt-5 grid gap-6 sm:grid-cols-2">{[["Billing model", c.model], ["Contract value", c.value], ["Effective date", "01 Oct 2026"], ["Contract end", "30 Sep 2027"], ["Payment terms", "Net 30 days"], ["Tax treatment", c.tax]].map(([a,b]) => <div key={a}><p className="text-xs text-slate-400">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div><div className="my-6 border-t" /><h3 className="font-bold">{c.model === "Project" ? "Milestone billing rules" : "Billing configuration"}</h3>{["Discovery & solution blueprint · 25%", "Implementation & UAT · 50%", "Go-live & handover · 25%"].map((x, i) => <div key={x} className="mt-3 flex items-center rounded-xl bg-slate-50 p-3 text-sm"><span className="mr-3 grid h-7 w-7 place-items-center rounded-lg bg-white text-xs font-bold shadow-sm">{i+1}</span><span className="font-medium">{x}</span><span className="ml-auto font-bold">{["₹8,12,500","₹16,25,000","₹8,12,500"][i]}</span></div>)}</div>
      <div className="space-y-5"><div className="panel p-5"><h3 className="font-bold">Tax decision</h3><div className="mt-4 rounded-xl bg-moss-50 p-4"><p className="text-sm font-bold text-moss-700">{c.tax}</p><p className="mt-1 text-xs text-moss-600">Auto-detected from customer and entity location</p></div></div><div className="panel p-5"><h3 className="font-bold">Notifications</h3><div className="mt-4 space-y-3">{["Milestone due · 7 days before", "Invoice generated · Immediately", "Expiry · 30 days before"].map((x) => <div className="flex gap-2 text-sm text-slate-600" key={x}><CheckCircle2 className="text-moss-500" size={16} />{x}</div>)}</div></div></div></div>
  </>;
}
export default ContractDetail;
